[tool.poetry]
name = "untested"
version = "0.1.0"
description = "not enough unit tests"
authors = ["Mitchell Tishmack <git@mitchty.net>"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"